server:
  port: 3721
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  ssl:
    key-store: classpath:certificate/wandering_verse.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
  http2:
    enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  application:
    name: WanderingVerse
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/wandering_verse
    username: root
    password: 123456
  elasticsearch:
    uris: http://39.106.10.8:9200
  kafka:
    bootstrap-servers: 39.106.10.8:9092
    topic:
      name: default_topic
    consumer:
      group-id: default_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:

minio:
  url: http://39.106.10.8:9000
  access-key: minio_root_user
  secret-key: minio_root_password
  bucket-name: bucket-default


langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://openrouter.ai/api/v1
      # 写入环境变量
      api-key: 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
      model-name: qwen/qwen3-235b-a22b:free
      # 输出请求日志
      log-requests: true
      # 输出响应日志
      log-responses: true

system:
  info:
    server:
    # 服务器提供商
    provider: AliCloud
    # 服务器租赁时间
    first-boot-time: 2025-04-25T16:42:21
    # 服务器到期时间
    lease-expiration-time: 2026-04-26T00:00:00