server:
  port: 3721
  ssl:
    key-store: classpath:certificate/wandering_verse.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
  http2:
    enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  application:
    name: WanderingVerse
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wandering_verse
    username: root
    password: 123456
  elasticsearch:
    uris: http://39.106.10.8:9200
  kafka:
    bootstrap-servers: 39.106.10.8:9092
    topic:
      name: default_topic
    consumer:
      group-id: default_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

minio:
  url: http://39.106.10.8:9000
  access-key: minio_root_user
  secret-key: minio_root_password
  bucket-name: bucket-default

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      # 写入环境变量
      api-key: ${AI_API_KEY}
      model-name: qwen-plus
      # 输出请求日志
      log-requests: true
      # 输出响应日志
      log-responses: true